import{a as f,S as q,i as w}from"./assets/vendor-HX_BPRhs.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function d(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=d(e);fetch(e.href,o)}})();f.defaults.baseURL="https://pixabay.com/api/";const m=async t=>{try{return(await f.get("",{params:t})).data}catch(r){throw console.error("Error fetching images:",r),r}},g=document.querySelector(".loader"),$=document.querySelector(".gallery");let u;function h(t){const r=t.hits.map(({webformatURL:d,largeImageURL:l,tags:e,likes:o,views:i,comments:S,downloads:E})=>`
    <li class="card">
      <a href="${l}">
        <img src="${d}" alt="${e}" loading="lazy"/>
      </a>
      <ul class="description">
        <li><p>Likes</p><span>${o}</span></li>
        <li><p>View</p><span>${i}</span></li>
        <li><p>Comments</p><span>${S}</span></li>
        <li><p>Download</p><span>${E}</span></li>
      </ul>
    </li>
  `).join("");$.insertAdjacentHTML("beforeend",r),u?u.refresh():u=new q(".gallery a",{captionsData:"alt"})}function n(){g.style.display="none"}function y(){g.style.display="block"}function L(t){return w.show({position:"topRight",color:"red",message:t})}const O=document.querySelector(".form"),b=document.querySelector(".inputFild"),c=document.querySelector(".btnSearchImg"),s=document.querySelector(".btnLoadMore"),v=document.querySelector(".gallery");c.disabled=!0;let x=1,p="";n();const a={key:"52935594-c28acfca0b14dad36f3e3eac1",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:x};b.addEventListener("input",t=>{if(p=t.target.value.trim(),p===""){c.disabled=!0;return}c.disabled=!1,a.q=p,a.page=1});O.addEventListener("submit",t=>{t.preventDefault(),b.value="",c.disabled=!0,v.innerHTML="",y(),s.classList.add("active"),m(a).then(r=>{if(r.totalHits===0){s.classList.add("active"),n(),L("Sorry, there are no images matching your search query. Please try again!");return}h(r),n(),s.classList.remove("active")}).catch(r=>{console.error("Failed to load images:",r)})});s.addEventListener("click",()=>{s.classList.add("active"),y(),a.page+=1,m(a).then(t=>{if(t.hits.length===0){s.classList.add("active"),n();return}h(t),s.classList.remove("active"),t.hits.length<a.per_page&&(s.classList.add("active"),L("We're sorry, but you've reached the end of search results.")),n();const{height:r}=v.getBoundingClientRect();window.scrollBy({top:r-100,behavior:"smooth"})}).catch(t=>{console.error("Failed to load images:",t)})});
//# sourceMappingURL=index.js.map
