import{a as f,S as w,i as $}from"./assets/vendor-HX_BPRhs.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function d(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=d(e);fetch(e.href,o)}})();f.defaults.baseURL="https://pixabay.com/api/";const g=async r=>{try{return(await f.get("",{params:r})).data}catch(t){throw console.error("Error fetching images:",t),t}},h=document.querySelector(".loader"),O=document.querySelector(".gallery");let u;function y(r){const t=r.hits.map(({webformatURL:d,largeImageURL:l,tags:e,likes:o,views:i,comments:E,downloads:q})=>`
    <li class="card">
      <a href="${l}">
        <img src="${d}" alt="${e}" loading="lazy"/>
      </a>
      <ul class="description">
        <li><p>Likes</p><span>${o}</span></li>
        <li><p>View</p><span>${i}</span></li>
        <li><p>Comments</p><span>${E}</span></li>
        <li><p>Download</p><span>${q}</span></li>
      </ul>
    </li>
  `).join("");O.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new w(".gallery a",{captionsData:"alt"})}function n(){h.style.display="none"}function L(){h.style.display="block"}function b(r){return $.show({position:"topRight",color:"red",message:r})}const x=document.querySelector(".form"),v=document.querySelector(".inputFild"),c=document.querySelector(".btnSearchImg"),s=document.querySelector(".btnLoadMore"),S=document.querySelector(".gallery");c.disabled=!0;let F=1,m=0,p="";n();const a={key:"52935594-c28acfca0b14dad36f3e3eac1",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:F};v.addEventListener("input",r=>{if(p=r.target.value.trim(),p===""){c.disabled=!0;return}c.disabled=!1,a.q=p,a.page=1});x.addEventListener("submit",r=>{r.preventDefault(),v.value="",c.disabled=!0,s.classList.add("active"),S.innerHTML="",L(),g(a).then(t=>{if(t.totalHits===0){s.classList.add("active"),n(),b("Sorry, there are no images matching your search query. Please try again!");return}y(t),n(),s.classList.remove("active")}).catch(t=>{console.error("Failed to load images:",t)})});s.addEventListener("click",()=>{s.classList.add("active"),L(),a.page+=1,g(a).then(r=>{if(m+=a.per_page,m>=r.totalHits){s.classList.add("active"),b("We're sorry, but you've reached the end of search results."),n();return}y(r),s.classList.remove("active"),n();const{height:t}=S.getBoundingClientRect();window.scrollBy({top:t-100,behavior:"smooth"})}).catch(r=>{console.error("Failed to load images:",r)})});
//# sourceMappingURL=index.js.map
