import{a as m,S as O,i as $}from"./assets/vendor-HX_BPRhs.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();m.defaults.baseURL="https://pixabay.com/api/";const y=async r=>{try{return(await m.get("",{params:r})).data}catch(e){throw console.error("Error fetching images:",e),e}},b=document.querySelector(".loader"),I=document.querySelector(".gallery");let h;function L(r){const e=r.hits.map(({webformatURL:a,largeImageURL:l,tags:t,likes:o,views:c,comments:q,downloads:v})=>`
    <li class="card">
      <a href="${l}">
        <img src="${a}" alt="${t}" loading="lazy"/>
      </a>
      <ul class="description">
        <li><p>Likes</p><span>${o}</span></li>
        <li><p>View</p><span>${c}</span></li>
        <li><p>Comments</p><span>${q}</span></li>
        <li><p>Download</p><span>${v}</span></li>
      </ul>
    </li>
  `).join("");I.insertAdjacentHTML("beforeend",e),h?h.refresh():h=new O(".gallery a",{captionsData:"alt"})}function s(){b.style.display="none"}function E(){b.style.display="block"}function f(r){return $.error({title:"Error",message:r,position:"topRight",timeout:4e3,closeOnClick:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"})}const M=document.querySelector(".form"),S=document.querySelector(".inputFild"),p=document.querySelector(".btnSearchImg"),i=document.querySelector(".btnLoadMore"),w=document.querySelector(".gallery");i.hidden=!0;p.disabled=!0;s();let d=1,g="",u=0;const n={key:"52935594-c28acfca0b14dad36f3e3eac1",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1};S.addEventListener("input",r=>{if(g=r.target.value.trim(),g===""){p.disabled=!0;return}p.disabled=!1});M.addEventListener("submit",async r=>{r.preventDefault(),p.disabled=!0,d=1,n.page=1,n.q=g,w.innerHTML="",i.hidden=!0,E();try{const e=await y(n);if(u=Number((e==null?void 0:e.totalHits)??0),!u){s(),f("Sorry, there are no images matching your search query. Please try again!");return}L(e),s();const a=d*n.per_page<u&&e.hits.length===n.per_page;i.hidden=!a}catch(e){console.error("Failed to load images:",e),s(),i.hidden=!0}finally{S.value=""}});i.addEventListener("click",async()=>{var r;i.hidden=!0,E();try{d+=1,n.page=d;const e=await y(n);if(!((r=e==null?void 0:e.hits)!=null&&r.length)){s(),f("We're sorry, but you've reached the end of search results.");return}L(e);const a=d*n.per_page>=u||e.hits.length<n.per_page;i.hidden=a,a&&f("We're sorry, but you've reached the end of search results."),s();const{height:l}=w.getBoundingClientRect();window.scrollBy({top:l-100,behavior:"smooth"})}catch(e){console.error("Failed to load images:",e),s(),i.hidden=!0}});
//# sourceMappingURL=index.js.map
